
import Dashboard from "@/component/dashboard";
import "./../style/globals.css";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-screen flex ">
        <Dashboard/>
        <div id="main-bg" className="w-full h-screen ">
          {children}
        </div>
      </body>
    </html>
  );
}
